package org.example.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.example.domain.po.Budgets;


@Mapper
public interface BudgetsMapper extends BaseMapper<Budgets> {


    @Insert("insert into budgets(budget_id,project_id,budget_amount,start_date,end_date,create_time)" +
            "values (#{budgetId},#{projectId},#{budgetAmount},#{startDate},#{endDate},now())")
    void addBudget(Budgets budgets);


    @Delete("delete from budgets where project_id = #{projectId}")
    void delectByProjectId(@Param(value = "projectId") Integer projectId);


//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-budgets
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    int deleteByPrimaryKey(Integer budgetId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-budgets
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    int insert(Budgets record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-budgets
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    Budgets selectByPrimaryKey(Integer budgetId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-budgets
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    List<Budgets> selectAll();
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-budgets
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    int updateByPrimaryKey(Budgets record);
//
//
//
}