package org.example.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Select;
import org.example.domain.po.Projects;

@Mapper
public interface ProjectsMapper extends BaseMapper<Projects> {


    @Insert("insert into projects(project_name,start_date,end_date,project_manager) " +
            "values(#{projectName},#{startDate},#{endDate},#{projectManager}) ")
    @Options(useGeneratedKeys=true, keyProperty="projectId", keyColumn="project_id")
    void addProject(Projects projects);


    @Select("select * from projects where project_name = #{projectName}")
    Projects findByProjectName(String projectName);
























//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-projects
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    int deleteByPrimaryKey(Integer projectId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-projects
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    int insert(Projects record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-projects
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    Projects selectByPrimaryKey(Integer projectId);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-projects
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    List<Projects> selectAll();
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table mm-projects
//     *
//     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
//     */
//    int updateByPrimaryKey(Projects record);
}