package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.math.BigInteger;
import java.time.LocalDateTime;

@Data
@TableName("processing")
public class Processing {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.processing_id
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    @TableId("processing_id")
    private Integer processingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.material_name
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.need_material_names
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private String needMaterialNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.material_ratio
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private String materialRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.warehouse_id
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private Integer warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.project_id
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.quantity
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.unit
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.create_time
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    @TableField("create_time")
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processing.update_time
     *
     * @mbggenerated Mon Dec 02 20:38:24 CST 2024
     */
    @TableField("update_time")
    private LocalDateTime updateTime;


}