package org.example.domain.po;



import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;


@Schema(description = "预算实体类")
@Data
@TableName(value = "budgets")
public class Budgets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-budgets.budget_id
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @TableId(value = "budget_id")
    @Schema(description = "预算id")
    private Integer budgetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-budgets.project_id
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */

    @Schema(description = "项目id")
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-budgets.budget_amount
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @Schema(description = "预算金额")
    private BigDecimal budgetAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-budgets.start_date
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @Schema(description = "项目开始时间")
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-budgets.end_date
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @Schema(description = "项目结束时间")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-budgets.CreatedBy
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @Schema(description = "创建时间")
    @TableField(value = "create_time")
    private LocalDateTime createTime;


}