package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigInteger;
import java.time.LocalDateTime;


@Data
@TableName("inventorys")
public class Inventorys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.inventory_id
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */

    @TableId("inventory_id")
    private Integer inventoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.material_name
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.warehouse_id
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private Integer warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.project_id
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private Integer projectId;




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.quantity
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.unit
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.min_quantity
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private BigInteger minQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.max_quantity
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */
    private BigInteger maxQuantity;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.create_time
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */

    @Schema(description = "创建时间")
    @TableField(value = "create_time")
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventorys.update_time
     *
     * @mbggenerated Sat Nov 30 15:38:13 CST 2024
     */

    @Schema(description = "创建时间")
    @TableField(value = "update_time")
    private LocalDateTime updateTime;


}