package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.util.Date;

@TableName(value = "projects")
@Data
public class Projects {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-projects.project_id
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @TableId(value = "project_id")
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-projects.project_name
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-projects.start_date
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-projects.end_date
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-projects.project_manager
     *
     * @mbggenerated Sat Nov 23 14:51:32 CST 2024
     */
    @TableField(value = "project_manager")
    private Integer projectManager;


}