package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Date;

@Data
@TableName(value = "purchases")
public class Purchases {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.purchase_id
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    @TableId(value = "purchase_id")
    private Integer purchaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.material_name
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.project_id
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.supplier_id
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.type
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.quantity
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.price
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.unit
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String unit;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.purchase_date
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private Date purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.create_time
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @TableField(value = "create_time")
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.update_time
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")

    @TableField(value = "update_time")
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.request_content
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String requestContent;

    private Integer deleted;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.status
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private Integer status;
}