package org.example.domain.po;


import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDateTime;

@Schema(description = "用户实体")
@Data
@TableName(value = "users")
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.user_id
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */

    @TableId(value = "user_id")
    @Schema(description = "用户id")
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.username
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */
    @Schema(description = "用户名")
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.password
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */
    @Schema(description = "用户密码")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.permission
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */
    @Schema(description = "用户权限")
    private Integer permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.email
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */

    @Schema(description = "用户邮箱")
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.phone_number
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */

    @Schema(description = "手机号")
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.create_time
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */
    @TableField(value = "create_time")
    @Schema(description = "创建时间")
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mm-users.update_time
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */
    @TableField(value = "update_time")
    @Schema(description = "更新时间")
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mm-users.user_id
     *
     * @return the value of mm-users.user_id
     *
     * @mbggenerated Sat Nov 23 14:00:29 CST 2024
     */

}