package org.example.domain.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;


@Data
public class PurchasesDto {

    private Integer purchaseId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.material_name
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.project_id
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.supplier_id
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String supplierName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.quantity
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.price
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.unit
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    private String unit;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases.purchase_date
     *
     * @mbggenerated Wed Nov 27 22:04:52 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date purchaseDate;


    private String requestContent;
    private String status;
}
