package org.example.domain.dto;

import lombok.Data;

import java.math.BigDecimal;

@Data
public class SuppliersDto {


    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.material_name
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.price
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.unit
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.contact_person
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.contact_phone
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.email
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.address
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String address;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.remarks
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */

    private String remarks;
}
