package org.example.domain.dto;

import lombok.Data;

import java.math.BigInteger;

@Data
public class ProvidedMaterialDto {
    private Integer providedMaterialId;
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.project_id
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String projectName;




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.quantity
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.unit
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String unit;
}
