package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Date;


@Data
@TableName(value = "purchases_return")
public class PurchasesReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.purchase_id
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    @TableId("purchase_return_id")
    private Integer purchaseReturnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.material_name
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.project_id
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.supplier_id
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.type
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.quantity
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.price
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.unit
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private String unit;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.purchase_date
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */

    @JsonFormat(pattern = "yyyy-MM-hh")
    private Date purchaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.create_time
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    @TableField("create_time")
    @JsonFormat(pattern = "yyyy-MM-hh HH:mm:ss")
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchases_return.request_content
     *
     * @mbggenerated Fri Nov 29 16:05:01 CST 2024
     */
    private String requestContent;
}