package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@TableName("suppliers")
public class Suppliers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.supplier_id
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    @TableId("supplier_id")
    private Integer supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.supplier_name
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.material_name
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.price
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.unit
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.contact_person
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.contact_phone
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.email
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.address
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.create_time
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @TableField(value = "create_time")
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.update_time
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @TableField(value = "update_time")
    private LocalDateTime updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suppliers.remarks
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */

    private String remarks;


}