package org.example.domain.po;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.math.BigInteger;
import java.time.LocalDateTime;
@Data
@TableName("outbound")
public class Outbound {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.outbound_id
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    @TableId("outbound_id")
    private Integer outboundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.material_name
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.warehouse_id
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    private Integer warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.project_id
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.quantity
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.outbound_date
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    @TableField("outbound_date")
    private LocalDateTime outboundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outbound.created_by
     *
     * @mbggenerated Mon Dec 02 13:44:33 CST 2024
     */
    private Integer createdBy;

}