package org.example.domain.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.math.BigInteger;
import java.time.LocalDateTime;

@Data
public class ProvidedMaterialVo {

    private Integer providedMaterialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.material_name
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String materialName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.project_id
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String projectName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.type
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.quantity
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private BigInteger quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.unit
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.create_time
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")

    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provided_material.update_time
     *
     * @mbggenerated Wed Nov 27 22:14:46 CST 2024
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")

    private LocalDateTime updateTime;
}
